import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// `base` targets GitHub Pages at https://<user>.github.io/Fitness-app/ and must
// match the repository name's casing exactly.
// Serving from a custom domain or a user-page root? Set BASE_PATH=/ at build time.
const base = process.env.BASE_PATH ?? '/Fitness-app/';

/**
 * Emits a service worker at build time. Written by hand rather than pulled from
 * a plugin, because the whole caching policy is fifteen lines and a dependency
 * here would outweigh it (see CLAUDE.md).
 *
 * The policy, and why:
 *  · Navigations are network-first. A new deploy is therefore picked up the
 *    next time the app is opened online — this is what stops the app going
 *    stale and needing the browser cache cleared by hand.
 *  · Everything under assets/ is content-hashed by Vite, so it is immutable and
 *    safe to serve cache-first, forever.
 *  · The cache name embeds the built asset names, so it changes on every real
 *    code change and the previous cache is dropped on activate.
 */
function serviceWorker(): Plugin {
  return {
    name: 'ridge-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((name) => name.startsWith('assets/'))
        .sort();

      // The hashed filenames are already a content fingerprint of the build.
      const version = assets.join('|') || String(Date.now());
      const precache = JSON.stringify([base, ...assets.map((a) => base + a)]);

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: `/* Generated by vite.config.ts — do not edit. */
const CACHE = 'ridge::${version}';
const PRECACHE = ${precache};
const INDEX = ${JSON.stringify(base)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;

  // Network-first for the document, so a fresh deploy always wins when online.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(INDEX, copy));
          return response;
        })
        .catch(() => caches.match(INDEX).then((hit) => hit || Response.error())),
    );
    return;
  }

  // Hashed assets are immutable: cache-first, and top the cache up on a miss.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`,
      });
    },
  };
}

export default defineConfig({
  base,
  plugins: [react(), serviceWorker()],
  build: {
    // The whole app is one bundle; there is nothing worth code-splitting in a
    // four-screen SPA and a single file caches better offline.
    chunkSizeWarningLimit: 400,
  },
});
